---

- name: Set fqdn for amppki
  ansible.builtin.debconf:
    name: amppki
    question: amppki/fqdn
    value: "{{ ampname }}"
    vtype: string

- name: Install amppki packages
  ansible.builtin.apt:
    name: amppki
    state: present

- name: Allow rabbitmq to read amppki server directory
  ansible.builtin.file:
    dest: "{{ amppki_keyfile | dirname }}"
    owner: root
    group: rabbitmq
    mode: u=rwx,g=rx,o=

- name: Allow rabbitmq to read amppki private key
  ansible.builtin.file:
    dest: "{{ amppki_keyfile }}"
    owner: root
    group: rabbitmq
    mode: u=rw,g=r,o=

# Apache configuration for amppki
- name: Configure /usr/share/amppki/amppki.conf
  ansible.builtin.template:
    src: "templates/amppki/amppki.conf"
    dest: "/usr/share/amppki/amppki.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: reload apache
