---

- name: Configure RabbitMQ
  ansible.builtin.template:
    src: "templates/rabbitmq/rabbitmq.config"
    dest: "/etc/rabbitmq/rabbitmq.config"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart rabbitmq
