---

- name: restart nntsc
  ansible.builtin.service:
    name: nntsc.service
    state: restarted

- name: restart rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server.service
    state: restarted

- name: reload apache
  ansible.builtin.service:
    name: apache2.service
    state: reloaded
