---

- name: restart nntsc
  service:
    name: nntsc.service
    state: restarted

- name: restart rabbitmq
  service:
    name: rabbitmq-server.service
    state: restarted

- name: reload apache
  service:
    name: apache2.service
    state: reloaded
